# Generated by Django 6.0.3 on 2026-03-20 20:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteNonviPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='NonviPay', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solde de NonviPay chez WalletX — doit refléter GATEWAY_EXTERNAL', max_digits=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte NonviPay',
                'verbose_name_plural': 'Compte NonviPay (singleton)',
            },
        ),
        migrations.CreateModel(
            name='CompteUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_telephone', models.CharField(max_length=20, unique=True)),
                ('nom_titulaire', models.CharField(default='Titulaire', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Solde virtuel en FCFA (100 000 FCFA par défaut)', max_digits=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte Utilisateur',
                'verbose_name_plural': 'Comptes Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionWalletX',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solde_nonvipay_avant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('solde_nonvipay_apres', models.DecimalField(decimal_places=2, max_digits=20)),
                ('solde_user_avant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('solde_user_apres', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference_externe', models.CharField(help_text="Référence envoyée par NonviPay — garantit l'idempotence", max_length=100, unique=True)),
                ('reference_walletx', models.CharField(max_length=100, unique=True)),
                ('sens', models.CharField(choices=[('DEPOT', 'Dépôt — User → NonviPay'), ('RETRAIT', 'Retrait — NonviPay → User')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_envoye', models.BooleanField(default=False)),
                ('webhook_response', models.TextField(blank=True)),
                ('webhook_envoye_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.compteutilisateur')),
            ],
            options={
                'verbose_name': 'Transaction WalletX',
                'verbose_name_plural': 'Transactions WalletX',
                'ordering': ['-created_at'],
            },
        ),
    ]
