# Generated by Django 6.0.3 on 2026-03-19 09:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteVirtuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_telephone', models.CharField(max_length=20, unique=True)),
                ('nom_titulaire', models.CharField(default='Titulaire', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Solde virtuel en FCFA', max_digits=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte Virtuel',
                'verbose_name_plural': 'Comptes Virtuels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionVirtuelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_externe', models.CharField(help_text='Référence envoyée par NonviPay', max_length=100, unique=True)),
                ('reference_walletx', models.CharField(max_length=100, unique=True)),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit — dépôt vers NonviPay'), ('CREDIT', 'Crédit — retrait depuis NonviPay')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=20)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='URL NonviPay à notifier après confirmation')),
                ('webhook_envoye', models.BooleanField(default=False)),
                ('webhook_response', models.TextField(blank=True)),
                ('webhook_envoye_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.comptevirtuel')),
            ],
            options={
                'verbose_name': 'Transaction Virtuelle',
                'verbose_name_plural': 'Transactions Virtuelles',
                'ordering': ['-created_at'],
            },
        ),
    ]
